
(define (problem travel) (:domain travel)
  (:objects
        car-0 - car
	fl - state
	hi - state
	id - state
	ky - state
	nj - state
	nv - state
	plane-0 - plane
	plane-1 - plane
	plane-2 - plane
	plane-3 - plane
	plane-4 - plane
  )
  (:goal (and
	(visited nj)
	(visited ky)
	(visited id)
	(visited hi)
	(visited fl)))
  (:init 
	(drive fl fl car-0)
	(drive fl hi car-0)
	(drive fl id car-0)
	(drive fl ky car-0)
	(drive fl nj car-0)
	(drive fl nv car-0)
	(drive hi fl car-0)
	(drive hi hi car-0)
	(drive hi id car-0)
	(drive hi ky car-0)
	(drive hi nj car-0)
	(drive hi nv car-0)
	(drive id fl car-0)
	(drive id hi car-0)
	(drive id id car-0)
	(drive id ky car-0)
	(drive id nj car-0)
	(drive id nv car-0)
	(drive ky fl car-0)
	(drive ky hi car-0)
	(drive ky id car-0)
	(drive ky ky car-0)
	(drive ky nj car-0)
	(drive ky nv car-0)
	(drive nj fl car-0)
	(drive nj hi car-0)
	(drive nj id car-0)
	(drive nj ky car-0)
	(drive nj nj car-0)
	(drive nj nv car-0)
	(drive nv fl car-0)
	(drive nv hi car-0)
	(drive nv id car-0)
	(drive nv ky car-0)
	(drive nv nj car-0)
	(drive nv nv car-0)
	(fly fl plane-0)
	(fly fl plane-1)
	(fly fl plane-2)
	(fly fl plane-3)
	(fly fl plane-4)
	(fly hi plane-0)
	(fly hi plane-1)
	(fly hi plane-2)
	(fly hi plane-3)
	(fly hi plane-4)
	(fly id plane-0)
	(fly id plane-1)
	(fly id plane-2)
	(fly id plane-3)
	(fly id plane-4)
	(fly ky plane-0)
	(fly ky plane-1)
	(fly ky plane-2)
	(fly ky plane-3)
	(fly ky plane-4)
	(fly nj plane-0)
	(fly nj plane-1)
	(fly nj plane-2)
	(fly nj plane-3)
	(fly nj plane-4)
	(fly nv plane-0)
	(fly nv plane-1)
	(fly nv plane-2)
	(fly nv plane-3)
	(fly nv plane-4)
	(walk fl)
	(walk hi)
	(walk id)
	(walk ky)
	(walk nj)
	(walk nv)
	(at nv)
	(isblueplane plane-4)
	(isbluestate fl)
	(isbluestate nv)
	(ispurplestate hi)
	(isredplane plane-0)
	(isredplane plane-1)
	(isredplane plane-2)
	(isredplane plane-3)
	(isredstate id)
	(isredstate ky)
	(isredstate nj)
	(planeavailable plane-0)
	(planeavailable plane-1)
	(planeavailable plane-2)
	(planeavailable plane-3)
	(planeavailable plane-4)
))
        