
(define (problem travel) (:domain travel)
  (:objects
        ak - state
	car-0 - car
	fl - state
	hi - state
	id - state
	ky - state
	mi - state
	ms - state
	nj - state
	nv - state
	plane-0 - plane
	plane-1 - plane
	plane-2 - plane
	plane-3 - plane
	plane-4 - plane
	plane-5 - plane
	plane-6 - plane
	plane-7 - plane
	plane-8 - plane
	wa - state
  )
  (:goal (and
	(visited nj)
	(visited ky)
	(visited id)
	(visited mi)
	(visited ms)
	(visited wa)))
  (:init 
	(Drive ak ak car-0)
	(Drive ak fl car-0)
	(Drive ak hi car-0)
	(Drive ak id car-0)
	(Drive ak ky car-0)
	(Drive ak mi car-0)
	(Drive ak ms car-0)
	(Drive ak nj car-0)
	(Drive ak nv car-0)
	(Drive ak wa car-0)
	(Drive fl ak car-0)
	(Drive fl fl car-0)
	(Drive fl hi car-0)
	(Drive fl id car-0)
	(Drive fl ky car-0)
	(Drive fl mi car-0)
	(Drive fl ms car-0)
	(Drive fl nj car-0)
	(Drive fl nv car-0)
	(Drive fl wa car-0)
	(Drive hi ak car-0)
	(Drive hi fl car-0)
	(Drive hi hi car-0)
	(Drive hi id car-0)
	(Drive hi ky car-0)
	(Drive hi mi car-0)
	(Drive hi ms car-0)
	(Drive hi nj car-0)
	(Drive hi nv car-0)
	(Drive hi wa car-0)
	(Drive id ak car-0)
	(Drive id fl car-0)
	(Drive id hi car-0)
	(Drive id id car-0)
	(Drive id ky car-0)
	(Drive id mi car-0)
	(Drive id ms car-0)
	(Drive id nj car-0)
	(Drive id nv car-0)
	(Drive id wa car-0)
	(Drive ky ak car-0)
	(Drive ky fl car-0)
	(Drive ky hi car-0)
	(Drive ky id car-0)
	(Drive ky ky car-0)
	(Drive ky mi car-0)
	(Drive ky ms car-0)
	(Drive ky nj car-0)
	(Drive ky nv car-0)
	(Drive ky wa car-0)
	(Drive mi ak car-0)
	(Drive mi fl car-0)
	(Drive mi hi car-0)
	(Drive mi id car-0)
	(Drive mi ky car-0)
	(Drive mi mi car-0)
	(Drive mi ms car-0)
	(Drive mi nj car-0)
	(Drive mi nv car-0)
	(Drive mi wa car-0)
	(Drive ms ak car-0)
	(Drive ms fl car-0)
	(Drive ms hi car-0)
	(Drive ms id car-0)
	(Drive ms ky car-0)
	(Drive ms mi car-0)
	(Drive ms ms car-0)
	(Drive ms nj car-0)
	(Drive ms nv car-0)
	(Drive ms wa car-0)
	(Drive nj ak car-0)
	(Drive nj fl car-0)
	(Drive nj hi car-0)
	(Drive nj id car-0)
	(Drive nj ky car-0)
	(Drive nj mi car-0)
	(Drive nj ms car-0)
	(Drive nj nj car-0)
	(Drive nj nv car-0)
	(Drive nj wa car-0)
	(Drive nv ak car-0)
	(Drive nv fl car-0)
	(Drive nv hi car-0)
	(Drive nv id car-0)
	(Drive nv ky car-0)
	(Drive nv mi car-0)
	(Drive nv ms car-0)
	(Drive nv nj car-0)
	(Drive nv nv car-0)
	(Drive nv wa car-0)
	(Drive wa ak car-0)
	(Drive wa fl car-0)
	(Drive wa hi car-0)
	(Drive wa id car-0)
	(Drive wa ky car-0)
	(Drive wa mi car-0)
	(Drive wa ms car-0)
	(Drive wa nj car-0)
	(Drive wa nv car-0)
	(Drive wa wa car-0)
	(Fly ak plane-0)
	(Fly ak plane-1)
	(Fly ak plane-2)
	(Fly ak plane-3)
	(Fly ak plane-4)
	(Fly ak plane-5)
	(Fly ak plane-6)
	(Fly ak plane-7)
	(Fly ak plane-8)
	(Fly fl plane-0)
	(Fly fl plane-1)
	(Fly fl plane-2)
	(Fly fl plane-3)
	(Fly fl plane-4)
	(Fly fl plane-5)
	(Fly fl plane-6)
	(Fly fl plane-7)
	(Fly fl plane-8)
	(Fly hi plane-0)
	(Fly hi plane-1)
	(Fly hi plane-2)
	(Fly hi plane-3)
	(Fly hi plane-4)
	(Fly hi plane-5)
	(Fly hi plane-6)
	(Fly hi plane-7)
	(Fly hi plane-8)
	(Fly id plane-0)
	(Fly id plane-1)
	(Fly id plane-2)
	(Fly id plane-3)
	(Fly id plane-4)
	(Fly id plane-5)
	(Fly id plane-6)
	(Fly id plane-7)
	(Fly id plane-8)
	(Fly ky plane-0)
	(Fly ky plane-1)
	(Fly ky plane-2)
	(Fly ky plane-3)
	(Fly ky plane-4)
	(Fly ky plane-5)
	(Fly ky plane-6)
	(Fly ky plane-7)
	(Fly ky plane-8)
	(Fly mi plane-0)
	(Fly mi plane-1)
	(Fly mi plane-2)
	(Fly mi plane-3)
	(Fly mi plane-4)
	(Fly mi plane-5)
	(Fly mi plane-6)
	(Fly mi plane-7)
	(Fly mi plane-8)
	(Fly ms plane-0)
	(Fly ms plane-1)
	(Fly ms plane-2)
	(Fly ms plane-3)
	(Fly ms plane-4)
	(Fly ms plane-5)
	(Fly ms plane-6)
	(Fly ms plane-7)
	(Fly ms plane-8)
	(Fly nj plane-0)
	(Fly nj plane-1)
	(Fly nj plane-2)
	(Fly nj plane-3)
	(Fly nj plane-4)
	(Fly nj plane-5)
	(Fly nj plane-6)
	(Fly nj plane-7)
	(Fly nj plane-8)
	(Fly nv plane-0)
	(Fly nv plane-1)
	(Fly nv plane-2)
	(Fly nv plane-3)
	(Fly nv plane-4)
	(Fly nv plane-5)
	(Fly nv plane-6)
	(Fly nv plane-7)
	(Fly nv plane-8)
	(Fly wa plane-0)
	(Fly wa plane-1)
	(Fly wa plane-2)
	(Fly wa plane-3)
	(Fly wa plane-4)
	(Fly wa plane-5)
	(Fly wa plane-6)
	(Fly wa plane-7)
	(Fly wa plane-8)
	(Walk ak)
	(Walk fl)
	(Walk hi)
	(Walk id)
	(Walk ky)
	(Walk mi)
	(Walk ms)
	(Walk nj)
	(Walk nv)
	(Walk wa)
	(at nv)
	(isblueplane plane-4)
	(isblueplane plane-5)
	(isblueplane plane-6)
	(isblueplane plane-7)
	(isblueplane plane-8)
	(isbluestate fl)
	(isbluestate mi)
	(isbluestate ms)
	(isbluestate nv)
	(isbluestate wa)
    (isbluestate hi)
    (isredstate ak)
    (Adjacent hi ak)
    (Adjacent ak hi)
	(isredplane plane-0)
	(isredplane plane-1)
	(isredplane plane-2)
	(isredplane plane-3)
	(isredstate id)
	(isredstate ky)
	(isredstate nj)
	(planeavailable plane-0)
	(planeavailable plane-1)
	(planeavailable plane-2)
	(planeavailable plane-3)
	(planeavailable plane-4)
	(planeavailable plane-5)
	(planeavailable plane-6)
	(planeavailable plane-7)
	(planeavailable plane-8)
))
        