(define (problem BLOCKS-4-1)
(:domain BLOCKS)
(:objects A - block C - block D - block B - block)
(:INIT (CLEAR B) (ONTABLE D) (ON B C) (ON C A) (ON A D) (HANDEMPTY))
(:goal (AND (ON D C) (ON C A) (ON A B)))
)