from .minecraft import render as minecraft_render
from .rearrangement import render as rearrangement_render
from .sokoban import render as sokoban_render
from .hanoi import render as hanoi_render
from .blocks import render as blocks_render
from .doors import render as doors_render
from .tsp import render as tsp_render
from .slidetile import render as slidetile_render
from .tireworld import render as tireworld_render
