
(define (problem travel) (:domain travel)
  (:objects
        car-0 - car
	fl - state
	hi - state
	id - state
	ky - state
	nj - state
	nv - state
	plane-0 - plane
	plane-1 - plane
	plane-2 - plane
	plane-3 - plane
	plane-4 - plane
  )
  (:goal (and
	(visited nj)
	(visited ky)
	(visited id)
	(visited hi)
	(visited fl)))
  (:init 
	(Drive fl fl car-0)
	(Drive fl hi car-0)
	(Drive fl id car-0)
	(Drive fl ky car-0)
	(Drive fl nj car-0)
	(Drive fl nv car-0)
	(Drive hi fl car-0)
	(Drive hi hi car-0)
	(Drive hi id car-0)
	(Drive hi ky car-0)
	(Drive hi nj car-0)
	(Drive hi nv car-0)
	(Drive id fl car-0)
	(Drive id hi car-0)
	(Drive id id car-0)
	(Drive id ky car-0)
	(Drive id nj car-0)
	(Drive id nv car-0)
	(Drive ky fl car-0)
	(Drive ky hi car-0)
	(Drive ky id car-0)
	(Drive ky ky car-0)
	(Drive ky nj car-0)
	(Drive ky nv car-0)
	(Drive nj fl car-0)
	(Drive nj hi car-0)
	(Drive nj id car-0)
	(Drive nj ky car-0)
	(Drive nj nj car-0)
	(Drive nj nv car-0)
	(Drive nv fl car-0)
	(Drive nv hi car-0)
	(Drive nv id car-0)
	(Drive nv ky car-0)
	(Drive nv nj car-0)
	(Drive nv nv car-0)
	(Fly fl plane-0)
	(Fly fl plane-1)
	(Fly fl plane-2)
	(Fly fl plane-3)
	(Fly fl plane-4)
	(Fly hi plane-0)
	(Fly hi plane-1)
	(Fly hi plane-2)
	(Fly hi plane-3)
	(Fly hi plane-4)
	(Fly id plane-0)
	(Fly id plane-1)
	(Fly id plane-2)
	(Fly id plane-3)
	(Fly id plane-4)
	(Fly ky plane-0)
	(Fly ky plane-1)
	(Fly ky plane-2)
	(Fly ky plane-3)
	(Fly ky plane-4)
	(Fly nj plane-0)
	(Fly nj plane-1)
	(Fly nj plane-2)
	(Fly nj plane-3)
	(Fly nj plane-4)
	(Fly nv plane-0)
	(Fly nv plane-1)
	(Fly nv plane-2)
	(Fly nv plane-3)
	(Fly nv plane-4)
	(Walk fl)
	(Walk hi)
	(Walk id)
	(Walk ky)
	(Walk nj)
	(Walk nv)
	(at nv)
	(isblueplane plane-4)
	(isbluestate fl)
	(isbluestate nv)
	(ispurplestate hi)
	(isredplane plane-0)
	(isredplane plane-1)
	(isredplane plane-2)
	(isredplane plane-3)
	(isredstate id)
	(isredstate ky)
	(isredstate nj)
	(planeavailable plane-0)
	(planeavailable plane-1)
	(planeavailable plane-2)
	(planeavailable plane-3)
	(planeavailable plane-4)
))
        