
(define (problem travel) (:domain travel)
  (:objects
        ca - state
	car-0 - car
	ky - state
	nj - state
	og - state
	pe - state
	plane-0 - plane
	plane-1 - plane
	tn - state
	tx - state
	wv - state
  )
  (:goal (and
	(visited tx)
	(visited tn)))
  (:init 
	(Drive ca ca car-0)
	(Drive ca ky car-0)
	(Drive ca nj car-0)
	(Drive ca og car-0)
	(Drive ca pe car-0)
	(Drive ca tn car-0)
	(Drive ca tx car-0)
	(Drive ca wv car-0)
	(Drive ky ca car-0)
	(Drive ky ky car-0)
	(Drive ky nj car-0)
	(Drive ky og car-0)
	(Drive ky pe car-0)
	(Drive ky tn car-0)
	(Drive ky tx car-0)
	(Drive ky wv car-0)
	(Drive nj ca car-0)
	(Drive nj ky car-0)
	(Drive nj nj car-0)
	(Drive nj og car-0)
	(Drive nj pe car-0)
	(Drive nj tn car-0)
	(Drive nj tx car-0)
	(Drive nj wv car-0)
	(Drive og ca car-0)
	(Drive og ky car-0)
	(Drive og nj car-0)
	(Drive og og car-0)
	(Drive og pe car-0)
	(Drive og tn car-0)
	(Drive og tx car-0)
	(Drive og wv car-0)
	(Drive pe ca car-0)
	(Drive pe ky car-0)
	(Drive pe nj car-0)
	(Drive pe og car-0)
	(Drive pe pe car-0)
	(Drive pe tn car-0)
	(Drive pe tx car-0)
	(Drive pe wv car-0)
	(Drive tn ca car-0)
	(Drive tn ky car-0)
	(Drive tn nj car-0)
	(Drive tn og car-0)
	(Drive tn pe car-0)
	(Drive tn tn car-0)
	(Drive tn tx car-0)
	(Drive tn wv car-0)
	(Drive tx ca car-0)
	(Drive tx ky car-0)
	(Drive tx nj car-0)
	(Drive tx og car-0)
	(Drive tx pe car-0)
	(Drive tx tn car-0)
	(Drive tx tx car-0)
	(Drive tx wv car-0)
	(Drive wv ca car-0)
	(Drive wv ky car-0)
	(Drive wv nj car-0)
	(Drive wv og car-0)
	(Drive wv pe car-0)
	(Drive wv tn car-0)
	(Drive wv tx car-0)
	(Drive wv wv car-0)
	(Fly ca plane-0)
	(Fly ca plane-1)
	(Fly ky plane-0)
	(Fly ky plane-1)
	(Fly nj plane-0)
	(Fly nj plane-1)
	(Fly og plane-0)
	(Fly og plane-1)
	(Fly pe plane-0)
	(Fly pe plane-1)
	(Fly tn plane-0)
	(Fly tn plane-1)
	(Fly tx plane-0)
	(Fly tx plane-1)
	(Fly wv plane-0)
	(Fly wv plane-1)
	(Walk ca)
	(Walk ky)
	(Walk nj)
	(Walk og)
	(Walk pe)
	(Walk tn)
	(Walk tx)
	(Walk wv)
	(adjacent ca og)
	(adjacent ky tn)
	(adjacent ky wv)
	(adjacent nj pe)
	(adjacent og ca)
	(adjacent pe nj)
	(adjacent pe wv)
	(adjacent tn ky)
	(adjacent wv ky)
	(adjacent wv pe)
	(at nj)
	(caravailable car-0)
	(isblueplane plane-1)
	(isbluestate ca)
	(isbluestate tx)
	(isredplane plane-0)
	(isredstate ky)
	(isredstate og)
	(planeavailable plane-0)
	(planeavailable plane-1)
))
        