
(define (problem travel) (:domain travel)
  (:objects
        car-0 - car
	car-1 - car
	car-2 - car
	car-3 - car
	fl - state
	hi - state
	ia - state
	id - state
	il - state
	mi - state
	mn - state
	mo - state
	nd - state
	ok - state
	plane-0 - plane
	plane-1 - plane
	plane-2 - plane
	plane-3 - plane
	sd - state
	tx - state
	wa - state
	wn - state
  )
  (:goal (and
	(visited wa)
	(visited fl)
	(visited ok)
	(visited id)))
  (:init 
	(Drive fl fl car-0)
	(Drive fl fl car-1)
	(Drive fl fl car-2)
	(Drive fl fl car-3)
	(Drive fl hi car-0)
	(Drive fl hi car-1)
	(Drive fl hi car-2)
	(Drive fl hi car-3)
	(Drive fl ia car-0)
	(Drive fl ia car-1)
	(Drive fl ia car-2)
	(Drive fl ia car-3)
	(Drive fl id car-0)
	(Drive fl id car-1)
	(Drive fl id car-2)
	(Drive fl id car-3)
	(Drive fl il car-0)
	(Drive fl il car-1)
	(Drive fl il car-2)
	(Drive fl il car-3)
	(Drive fl mi car-0)
	(Drive fl mi car-1)
	(Drive fl mi car-2)
	(Drive fl mi car-3)
	(Drive fl mn car-0)
	(Drive fl mn car-1)
	(Drive fl mn car-2)
	(Drive fl mn car-3)
	(Drive fl mo car-0)
	(Drive fl mo car-1)
	(Drive fl mo car-2)
	(Drive fl mo car-3)
	(Drive fl nd car-0)
	(Drive fl nd car-1)
	(Drive fl nd car-2)
	(Drive fl nd car-3)
	(Drive fl ok car-0)
	(Drive fl ok car-1)
	(Drive fl ok car-2)
	(Drive fl ok car-3)
	(Drive fl sd car-0)
	(Drive fl sd car-1)
	(Drive fl sd car-2)
	(Drive fl sd car-3)
	(Drive fl tx car-0)
	(Drive fl tx car-1)
	(Drive fl tx car-2)
	(Drive fl tx car-3)
	(Drive fl wa car-0)
	(Drive fl wa car-1)
	(Drive fl wa car-2)
	(Drive fl wa car-3)
	(Drive fl wn car-0)
	(Drive fl wn car-1)
	(Drive fl wn car-2)
	(Drive fl wn car-3)
	(Drive hi fl car-0)
	(Drive hi fl car-1)
	(Drive hi fl car-2)
	(Drive hi fl car-3)
	(Drive hi hi car-0)
	(Drive hi hi car-1)
	(Drive hi hi car-2)
	(Drive hi hi car-3)
	(Drive hi ia car-0)
	(Drive hi ia car-1)
	(Drive hi ia car-2)
	(Drive hi ia car-3)
	(Drive hi id car-0)
	(Drive hi id car-1)
	(Drive hi id car-2)
	(Drive hi id car-3)
	(Drive hi il car-0)
	(Drive hi il car-1)
	(Drive hi il car-2)
	(Drive hi il car-3)
	(Drive hi mi car-0)
	(Drive hi mi car-1)
	(Drive hi mi car-2)
	(Drive hi mi car-3)
	(Drive hi mn car-0)
	(Drive hi mn car-1)
	(Drive hi mn car-2)
	(Drive hi mn car-3)
	(Drive hi mo car-0)
	(Drive hi mo car-1)
	(Drive hi mo car-2)
	(Drive hi mo car-3)
	(Drive hi nd car-0)
	(Drive hi nd car-1)
	(Drive hi nd car-2)
	(Drive hi nd car-3)
	(Drive hi ok car-0)
	(Drive hi ok car-1)
	(Drive hi ok car-2)
	(Drive hi ok car-3)
	(Drive hi sd car-0)
	(Drive hi sd car-1)
	(Drive hi sd car-2)
	(Drive hi sd car-3)
	(Drive hi tx car-0)
	(Drive hi tx car-1)
	(Drive hi tx car-2)
	(Drive hi tx car-3)
	(Drive hi wa car-0)
	(Drive hi wa car-1)
	(Drive hi wa car-2)
	(Drive hi wa car-3)
	(Drive hi wn car-0)
	(Drive hi wn car-1)
	(Drive hi wn car-2)
	(Drive hi wn car-3)
	(Drive ia fl car-0)
	(Drive ia fl car-1)
	(Drive ia fl car-2)
	(Drive ia fl car-3)
	(Drive ia hi car-0)
	(Drive ia hi car-1)
	(Drive ia hi car-2)
	(Drive ia hi car-3)
	(Drive ia ia car-0)
	(Drive ia ia car-1)
	(Drive ia ia car-2)
	(Drive ia ia car-3)
	(Drive ia id car-0)
	(Drive ia id car-1)
	(Drive ia id car-2)
	(Drive ia id car-3)
	(Drive ia il car-0)
	(Drive ia il car-1)
	(Drive ia il car-2)
	(Drive ia il car-3)
	(Drive ia mi car-0)
	(Drive ia mi car-1)
	(Drive ia mi car-2)
	(Drive ia mi car-3)
	(Drive ia mn car-0)
	(Drive ia mn car-1)
	(Drive ia mn car-2)
	(Drive ia mn car-3)
	(Drive ia mo car-0)
	(Drive ia mo car-1)
	(Drive ia mo car-2)
	(Drive ia mo car-3)
	(Drive ia nd car-0)
	(Drive ia nd car-1)
	(Drive ia nd car-2)
	(Drive ia nd car-3)
	(Drive ia ok car-0)
	(Drive ia ok car-1)
	(Drive ia ok car-2)
	(Drive ia ok car-3)
	(Drive ia sd car-0)
	(Drive ia sd car-1)
	(Drive ia sd car-2)
	(Drive ia sd car-3)
	(Drive ia tx car-0)
	(Drive ia tx car-1)
	(Drive ia tx car-2)
	(Drive ia tx car-3)
	(Drive ia wa car-0)
	(Drive ia wa car-1)
	(Drive ia wa car-2)
	(Drive ia wa car-3)
	(Drive ia wn car-0)
	(Drive ia wn car-1)
	(Drive ia wn car-2)
	(Drive ia wn car-3)
	(Drive id fl car-0)
	(Drive id fl car-1)
	(Drive id fl car-2)
	(Drive id fl car-3)
	(Drive id hi car-0)
	(Drive id hi car-1)
	(Drive id hi car-2)
	(Drive id hi car-3)
	(Drive id ia car-0)
	(Drive id ia car-1)
	(Drive id ia car-2)
	(Drive id ia car-3)
	(Drive id id car-0)
	(Drive id id car-1)
	(Drive id id car-2)
	(Drive id id car-3)
	(Drive id il car-0)
	(Drive id il car-1)
	(Drive id il car-2)
	(Drive id il car-3)
	(Drive id mi car-0)
	(Drive id mi car-1)
	(Drive id mi car-2)
	(Drive id mi car-3)
	(Drive id mn car-0)
	(Drive id mn car-1)
	(Drive id mn car-2)
	(Drive id mn car-3)
	(Drive id mo car-0)
	(Drive id mo car-1)
	(Drive id mo car-2)
	(Drive id mo car-3)
	(Drive id nd car-0)
	(Drive id nd car-1)
	(Drive id nd car-2)
	(Drive id nd car-3)
	(Drive id ok car-0)
	(Drive id ok car-1)
	(Drive id ok car-2)
	(Drive id ok car-3)
	(Drive id sd car-0)
	(Drive id sd car-1)
	(Drive id sd car-2)
	(Drive id sd car-3)
	(Drive id tx car-0)
	(Drive id tx car-1)
	(Drive id tx car-2)
	(Drive id tx car-3)
	(Drive id wa car-0)
	(Drive id wa car-1)
	(Drive id wa car-2)
	(Drive id wa car-3)
	(Drive id wn car-0)
	(Drive id wn car-1)
	(Drive id wn car-2)
	(Drive id wn car-3)
	(Drive il fl car-0)
	(Drive il fl car-1)
	(Drive il fl car-2)
	(Drive il fl car-3)
	(Drive il hi car-0)
	(Drive il hi car-1)
	(Drive il hi car-2)
	(Drive il hi car-3)
	(Drive il ia car-0)
	(Drive il ia car-1)
	(Drive il ia car-2)
	(Drive il ia car-3)
	(Drive il id car-0)
	(Drive il id car-1)
	(Drive il id car-2)
	(Drive il id car-3)
	(Drive il il car-0)
	(Drive il il car-1)
	(Drive il il car-2)
	(Drive il il car-3)
	(Drive il mi car-0)
	(Drive il mi car-1)
	(Drive il mi car-2)
	(Drive il mi car-3)
	(Drive il mn car-0)
	(Drive il mn car-1)
	(Drive il mn car-2)
	(Drive il mn car-3)
	(Drive il mo car-0)
	(Drive il mo car-1)
	(Drive il mo car-2)
	(Drive il mo car-3)
	(Drive il nd car-0)
	(Drive il nd car-1)
	(Drive il nd car-2)
	(Drive il nd car-3)
	(Drive il ok car-0)
	(Drive il ok car-1)
	(Drive il ok car-2)
	(Drive il ok car-3)
	(Drive il sd car-0)
	(Drive il sd car-1)
	(Drive il sd car-2)
	(Drive il sd car-3)
	(Drive il tx car-0)
	(Drive il tx car-1)
	(Drive il tx car-2)
	(Drive il tx car-3)
	(Drive il wa car-0)
	(Drive il wa car-1)
	(Drive il wa car-2)
	(Drive il wa car-3)
	(Drive il wn car-0)
	(Drive il wn car-1)
	(Drive il wn car-2)
	(Drive il wn car-3)
	(Drive mi fl car-0)
	(Drive mi fl car-1)
	(Drive mi fl car-2)
	(Drive mi fl car-3)
	(Drive mi hi car-0)
	(Drive mi hi car-1)
	(Drive mi hi car-2)
	(Drive mi hi car-3)
	(Drive mi ia car-0)
	(Drive mi ia car-1)
	(Drive mi ia car-2)
	(Drive mi ia car-3)
	(Drive mi id car-0)
	(Drive mi id car-1)
	(Drive mi id car-2)
	(Drive mi id car-3)
	(Drive mi il car-0)
	(Drive mi il car-1)
	(Drive mi il car-2)
	(Drive mi il car-3)
	(Drive mi mi car-0)
	(Drive mi mi car-1)
	(Drive mi mi car-2)
	(Drive mi mi car-3)
	(Drive mi mn car-0)
	(Drive mi mn car-1)
	(Drive mi mn car-2)
	(Drive mi mn car-3)
	(Drive mi mo car-0)
	(Drive mi mo car-1)
	(Drive mi mo car-2)
	(Drive mi mo car-3)
	(Drive mi nd car-0)
	(Drive mi nd car-1)
	(Drive mi nd car-2)
	(Drive mi nd car-3)
	(Drive mi ok car-0)
	(Drive mi ok car-1)
	(Drive mi ok car-2)
	(Drive mi ok car-3)
	(Drive mi sd car-0)
	(Drive mi sd car-1)
	(Drive mi sd car-2)
	(Drive mi sd car-3)
	(Drive mi tx car-0)
	(Drive mi tx car-1)
	(Drive mi tx car-2)
	(Drive mi tx car-3)
	(Drive mi wa car-0)
	(Drive mi wa car-1)
	(Drive mi wa car-2)
	(Drive mi wa car-3)
	(Drive mi wn car-0)
	(Drive mi wn car-1)
	(Drive mi wn car-2)
	(Drive mi wn car-3)
	(Drive mn fl car-0)
	(Drive mn fl car-1)
	(Drive mn fl car-2)
	(Drive mn fl car-3)
	(Drive mn hi car-0)
	(Drive mn hi car-1)
	(Drive mn hi car-2)
	(Drive mn hi car-3)
	(Drive mn ia car-0)
	(Drive mn ia car-1)
	(Drive mn ia car-2)
	(Drive mn ia car-3)
	(Drive mn id car-0)
	(Drive mn id car-1)
	(Drive mn id car-2)
	(Drive mn id car-3)
	(Drive mn il car-0)
	(Drive mn il car-1)
	(Drive mn il car-2)
	(Drive mn il car-3)
	(Drive mn mi car-0)
	(Drive mn mi car-1)
	(Drive mn mi car-2)
	(Drive mn mi car-3)
	(Drive mn mn car-0)
	(Drive mn mn car-1)
	(Drive mn mn car-2)
	(Drive mn mn car-3)
	(Drive mn mo car-0)
	(Drive mn mo car-1)
	(Drive mn mo car-2)
	(Drive mn mo car-3)
	(Drive mn nd car-0)
	(Drive mn nd car-1)
	(Drive mn nd car-2)
	(Drive mn nd car-3)
	(Drive mn ok car-0)
	(Drive mn ok car-1)
	(Drive mn ok car-2)
	(Drive mn ok car-3)
	(Drive mn sd car-0)
	(Drive mn sd car-1)
	(Drive mn sd car-2)
	(Drive mn sd car-3)
	(Drive mn tx car-0)
	(Drive mn tx car-1)
	(Drive mn tx car-2)
	(Drive mn tx car-3)
	(Drive mn wa car-0)
	(Drive mn wa car-1)
	(Drive mn wa car-2)
	(Drive mn wa car-3)
	(Drive mn wn car-0)
	(Drive mn wn car-1)
	(Drive mn wn car-2)
	(Drive mn wn car-3)
	(Drive mo fl car-0)
	(Drive mo fl car-1)
	(Drive mo fl car-2)
	(Drive mo fl car-3)
	(Drive mo hi car-0)
	(Drive mo hi car-1)
	(Drive mo hi car-2)
	(Drive mo hi car-3)
	(Drive mo ia car-0)
	(Drive mo ia car-1)
	(Drive mo ia car-2)
	(Drive mo ia car-3)
	(Drive mo id car-0)
	(Drive mo id car-1)
	(Drive mo id car-2)
	(Drive mo id car-3)
	(Drive mo il car-0)
	(Drive mo il car-1)
	(Drive mo il car-2)
	(Drive mo il car-3)
	(Drive mo mi car-0)
	(Drive mo mi car-1)
	(Drive mo mi car-2)
	(Drive mo mi car-3)
	(Drive mo mn car-0)
	(Drive mo mn car-1)
	(Drive mo mn car-2)
	(Drive mo mn car-3)
	(Drive mo mo car-0)
	(Drive mo mo car-1)
	(Drive mo mo car-2)
	(Drive mo mo car-3)
	(Drive mo nd car-0)
	(Drive mo nd car-1)
	(Drive mo nd car-2)
	(Drive mo nd car-3)
	(Drive mo ok car-0)
	(Drive mo ok car-1)
	(Drive mo ok car-2)
	(Drive mo ok car-3)
	(Drive mo sd car-0)
	(Drive mo sd car-1)
	(Drive mo sd car-2)
	(Drive mo sd car-3)
	(Drive mo tx car-0)
	(Drive mo tx car-1)
	(Drive mo tx car-2)
	(Drive mo tx car-3)
	(Drive mo wa car-0)
	(Drive mo wa car-1)
	(Drive mo wa car-2)
	(Drive mo wa car-3)
	(Drive mo wn car-0)
	(Drive mo wn car-1)
	(Drive mo wn car-2)
	(Drive mo wn car-3)
	(Drive nd fl car-0)
	(Drive nd fl car-1)
	(Drive nd fl car-2)
	(Drive nd fl car-3)
	(Drive nd hi car-0)
	(Drive nd hi car-1)
	(Drive nd hi car-2)
	(Drive nd hi car-3)
	(Drive nd ia car-0)
	(Drive nd ia car-1)
	(Drive nd ia car-2)
	(Drive nd ia car-3)
	(Drive nd id car-0)
	(Drive nd id car-1)
	(Drive nd id car-2)
	(Drive nd id car-3)
	(Drive nd il car-0)
	(Drive nd il car-1)
	(Drive nd il car-2)
	(Drive nd il car-3)
	(Drive nd mi car-0)
	(Drive nd mi car-1)
	(Drive nd mi car-2)
	(Drive nd mi car-3)
	(Drive nd mn car-0)
	(Drive nd mn car-1)
	(Drive nd mn car-2)
	(Drive nd mn car-3)
	(Drive nd mo car-0)
	(Drive nd mo car-1)
	(Drive nd mo car-2)
	(Drive nd mo car-3)
	(Drive nd nd car-0)
	(Drive nd nd car-1)
	(Drive nd nd car-2)
	(Drive nd nd car-3)
	(Drive nd ok car-0)
	(Drive nd ok car-1)
	(Drive nd ok car-2)
	(Drive nd ok car-3)
	(Drive nd sd car-0)
	(Drive nd sd car-1)
	(Drive nd sd car-2)
	(Drive nd sd car-3)
	(Drive nd tx car-0)
	(Drive nd tx car-1)
	(Drive nd tx car-2)
	(Drive nd tx car-3)
	(Drive nd wa car-0)
	(Drive nd wa car-1)
	(Drive nd wa car-2)
	(Drive nd wa car-3)
	(Drive nd wn car-0)
	(Drive nd wn car-1)
	(Drive nd wn car-2)
	(Drive nd wn car-3)
	(Drive ok fl car-0)
	(Drive ok fl car-1)
	(Drive ok fl car-2)
	(Drive ok fl car-3)
	(Drive ok hi car-0)
	(Drive ok hi car-1)
	(Drive ok hi car-2)
	(Drive ok hi car-3)
	(Drive ok ia car-0)
	(Drive ok ia car-1)
	(Drive ok ia car-2)
	(Drive ok ia car-3)
	(Drive ok id car-0)
	(Drive ok id car-1)
	(Drive ok id car-2)
	(Drive ok id car-3)
	(Drive ok il car-0)
	(Drive ok il car-1)
	(Drive ok il car-2)
	(Drive ok il car-3)
	(Drive ok mi car-0)
	(Drive ok mi car-1)
	(Drive ok mi car-2)
	(Drive ok mi car-3)
	(Drive ok mn car-0)
	(Drive ok mn car-1)
	(Drive ok mn car-2)
	(Drive ok mn car-3)
	(Drive ok mo car-0)
	(Drive ok mo car-1)
	(Drive ok mo car-2)
	(Drive ok mo car-3)
	(Drive ok nd car-0)
	(Drive ok nd car-1)
	(Drive ok nd car-2)
	(Drive ok nd car-3)
	(Drive ok ok car-0)
	(Drive ok ok car-1)
	(Drive ok ok car-2)
	(Drive ok ok car-3)
	(Drive ok sd car-0)
	(Drive ok sd car-1)
	(Drive ok sd car-2)
	(Drive ok sd car-3)
	(Drive ok tx car-0)
	(Drive ok tx car-1)
	(Drive ok tx car-2)
	(Drive ok tx car-3)
	(Drive ok wa car-0)
	(Drive ok wa car-1)
	(Drive ok wa car-2)
	(Drive ok wa car-3)
	(Drive ok wn car-0)
	(Drive ok wn car-1)
	(Drive ok wn car-2)
	(Drive ok wn car-3)
	(Drive sd fl car-0)
	(Drive sd fl car-1)
	(Drive sd fl car-2)
	(Drive sd fl car-3)
	(Drive sd hi car-0)
	(Drive sd hi car-1)
	(Drive sd hi car-2)
	(Drive sd hi car-3)
	(Drive sd ia car-0)
	(Drive sd ia car-1)
	(Drive sd ia car-2)
	(Drive sd ia car-3)
	(Drive sd id car-0)
	(Drive sd id car-1)
	(Drive sd id car-2)
	(Drive sd id car-3)
	(Drive sd il car-0)
	(Drive sd il car-1)
	(Drive sd il car-2)
	(Drive sd il car-3)
	(Drive sd mi car-0)
	(Drive sd mi car-1)
	(Drive sd mi car-2)
	(Drive sd mi car-3)
	(Drive sd mn car-0)
	(Drive sd mn car-1)
	(Drive sd mn car-2)
	(Drive sd mn car-3)
	(Drive sd mo car-0)
	(Drive sd mo car-1)
	(Drive sd mo car-2)
	(Drive sd mo car-3)
	(Drive sd nd car-0)
	(Drive sd nd car-1)
	(Drive sd nd car-2)
	(Drive sd nd car-3)
	(Drive sd ok car-0)
	(Drive sd ok car-1)
	(Drive sd ok car-2)
	(Drive sd ok car-3)
	(Drive sd sd car-0)
	(Drive sd sd car-1)
	(Drive sd sd car-2)
	(Drive sd sd car-3)
	(Drive sd tx car-0)
	(Drive sd tx car-1)
	(Drive sd tx car-2)
	(Drive sd tx car-3)
	(Drive sd wa car-0)
	(Drive sd wa car-1)
	(Drive sd wa car-2)
	(Drive sd wa car-3)
	(Drive sd wn car-0)
	(Drive sd wn car-1)
	(Drive sd wn car-2)
	(Drive sd wn car-3)
	(Drive tx fl car-0)
	(Drive tx fl car-1)
	(Drive tx fl car-2)
	(Drive tx fl car-3)
	(Drive tx hi car-0)
	(Drive tx hi car-1)
	(Drive tx hi car-2)
	(Drive tx hi car-3)
	(Drive tx ia car-0)
	(Drive tx ia car-1)
	(Drive tx ia car-2)
	(Drive tx ia car-3)
	(Drive tx id car-0)
	(Drive tx id car-1)
	(Drive tx id car-2)
	(Drive tx id car-3)
	(Drive tx il car-0)
	(Drive tx il car-1)
	(Drive tx il car-2)
	(Drive tx il car-3)
	(Drive tx mi car-0)
	(Drive tx mi car-1)
	(Drive tx mi car-2)
	(Drive tx mi car-3)
	(Drive tx mn car-0)
	(Drive tx mn car-1)
	(Drive tx mn car-2)
	(Drive tx mn car-3)
	(Drive tx mo car-0)
	(Drive tx mo car-1)
	(Drive tx mo car-2)
	(Drive tx mo car-3)
	(Drive tx nd car-0)
	(Drive tx nd car-1)
	(Drive tx nd car-2)
	(Drive tx nd car-3)
	(Drive tx ok car-0)
	(Drive tx ok car-1)
	(Drive tx ok car-2)
	(Drive tx ok car-3)
	(Drive tx sd car-0)
	(Drive tx sd car-1)
	(Drive tx sd car-2)
	(Drive tx sd car-3)
	(Drive tx tx car-0)
	(Drive tx tx car-1)
	(Drive tx tx car-2)
	(Drive tx tx car-3)
	(Drive tx wa car-0)
	(Drive tx wa car-1)
	(Drive tx wa car-2)
	(Drive tx wa car-3)
	(Drive tx wn car-0)
	(Drive tx wn car-1)
	(Drive tx wn car-2)
	(Drive tx wn car-3)
	(Drive wa fl car-0)
	(Drive wa fl car-1)
	(Drive wa fl car-2)
	(Drive wa fl car-3)
	(Drive wa hi car-0)
	(Drive wa hi car-1)
	(Drive wa hi car-2)
	(Drive wa hi car-3)
	(Drive wa ia car-0)
	(Drive wa ia car-1)
	(Drive wa ia car-2)
	(Drive wa ia car-3)
	(Drive wa id car-0)
	(Drive wa id car-1)
	(Drive wa id car-2)
	(Drive wa id car-3)
	(Drive wa il car-0)
	(Drive wa il car-1)
	(Drive wa il car-2)
	(Drive wa il car-3)
	(Drive wa mi car-0)
	(Drive wa mi car-1)
	(Drive wa mi car-2)
	(Drive wa mi car-3)
	(Drive wa mn car-0)
	(Drive wa mn car-1)
	(Drive wa mn car-2)
	(Drive wa mn car-3)
	(Drive wa mo car-0)
	(Drive wa mo car-1)
	(Drive wa mo car-2)
	(Drive wa mo car-3)
	(Drive wa nd car-0)
	(Drive wa nd car-1)
	(Drive wa nd car-2)
	(Drive wa nd car-3)
	(Drive wa ok car-0)
	(Drive wa ok car-1)
	(Drive wa ok car-2)
	(Drive wa ok car-3)
	(Drive wa sd car-0)
	(Drive wa sd car-1)
	(Drive wa sd car-2)
	(Drive wa sd car-3)
	(Drive wa tx car-0)
	(Drive wa tx car-1)
	(Drive wa tx car-2)
	(Drive wa tx car-3)
	(Drive wa wa car-0)
	(Drive wa wa car-1)
	(Drive wa wa car-2)
	(Drive wa wa car-3)
	(Drive wa wn car-0)
	(Drive wa wn car-1)
	(Drive wa wn car-2)
	(Drive wa wn car-3)
	(Drive wn fl car-0)
	(Drive wn fl car-1)
	(Drive wn fl car-2)
	(Drive wn fl car-3)
	(Drive wn hi car-0)
	(Drive wn hi car-1)
	(Drive wn hi car-2)
	(Drive wn hi car-3)
	(Drive wn ia car-0)
	(Drive wn ia car-1)
	(Drive wn ia car-2)
	(Drive wn ia car-3)
	(Drive wn id car-0)
	(Drive wn id car-1)
	(Drive wn id car-2)
	(Drive wn id car-3)
	(Drive wn il car-0)
	(Drive wn il car-1)
	(Drive wn il car-2)
	(Drive wn il car-3)
	(Drive wn mi car-0)
	(Drive wn mi car-1)
	(Drive wn mi car-2)
	(Drive wn mi car-3)
	(Drive wn mn car-0)
	(Drive wn mn car-1)
	(Drive wn mn car-2)
	(Drive wn mn car-3)
	(Drive wn mo car-0)
	(Drive wn mo car-1)
	(Drive wn mo car-2)
	(Drive wn mo car-3)
	(Drive wn nd car-0)
	(Drive wn nd car-1)
	(Drive wn nd car-2)
	(Drive wn nd car-3)
	(Drive wn ok car-0)
	(Drive wn ok car-1)
	(Drive wn ok car-2)
	(Drive wn ok car-3)
	(Drive wn sd car-0)
	(Drive wn sd car-1)
	(Drive wn sd car-2)
	(Drive wn sd car-3)
	(Drive wn tx car-0)
	(Drive wn tx car-1)
	(Drive wn tx car-2)
	(Drive wn tx car-3)
	(Drive wn wa car-0)
	(Drive wn wa car-1)
	(Drive wn wa car-2)
	(Drive wn wa car-3)
	(Drive wn wn car-0)
	(Drive wn wn car-1)
	(Drive wn wn car-2)
	(Drive wn wn car-3)
	(Fly fl plane-0)
	(Fly fl plane-1)
	(Fly fl plane-2)
	(Fly fl plane-3)
	(Fly hi plane-0)
	(Fly hi plane-1)
	(Fly hi plane-2)
	(Fly hi plane-3)
	(Fly ia plane-0)
	(Fly ia plane-1)
	(Fly ia plane-2)
	(Fly ia plane-3)
	(Fly id plane-0)
	(Fly id plane-1)
	(Fly id plane-2)
	(Fly id plane-3)
	(Fly il plane-0)
	(Fly il plane-1)
	(Fly il plane-2)
	(Fly il plane-3)
	(Fly mi plane-0)
	(Fly mi plane-1)
	(Fly mi plane-2)
	(Fly mi plane-3)
	(Fly mn plane-0)
	(Fly mn plane-1)
	(Fly mn plane-2)
	(Fly mn plane-3)
	(Fly mo plane-0)
	(Fly mo plane-1)
	(Fly mo plane-2)
	(Fly mo plane-3)
	(Fly nd plane-0)
	(Fly nd plane-1)
	(Fly nd plane-2)
	(Fly nd plane-3)
	(Fly ok plane-0)
	(Fly ok plane-1)
	(Fly ok plane-2)
	(Fly ok plane-3)
	(Fly sd plane-0)
	(Fly sd plane-1)
	(Fly sd plane-2)
	(Fly sd plane-3)
	(Fly tx plane-0)
	(Fly tx plane-1)
	(Fly tx plane-2)
	(Fly tx plane-3)
	(Fly wa plane-0)
	(Fly wa plane-1)
	(Fly wa plane-2)
	(Fly wa plane-3)
	(Fly wn plane-0)
	(Fly wn plane-1)
	(Fly wn plane-2)
	(Fly wn plane-3)
	(Walk fl)
	(Walk hi)
	(Walk ia)
	(Walk id)
	(Walk il)
	(Walk mi)
	(Walk mn)
	(Walk mo)
	(Walk nd)
	(Walk ok)
	(Walk sd)
	(Walk tx)
	(Walk wa)
	(Walk wn)
	(adjacent ia il)
	(adjacent ia mn)
	(adjacent ia sd)
	(adjacent ia wn)
	(adjacent id mo)
	(adjacent id wa)
	(adjacent il ia)
	(adjacent mi wn)
	(adjacent mn ia)
	(adjacent mn nd)
	(adjacent mn sd)
	(adjacent mn wn)
	(adjacent mo id)
	(adjacent mo nd)
	(adjacent mo sd)
	(adjacent nd mn)
	(adjacent nd mo)
	(adjacent nd sd)
	(adjacent ok tx)
	(adjacent sd ia)
	(adjacent sd mn)
	(adjacent sd mo)
	(adjacent sd nd)
	(adjacent tx ok)
	(adjacent wa id)
	(adjacent wn ia)
	(adjacent wn mi)
	(adjacent wn mn)
	(at sd)
	(caravailable car-0)
	(caravailable car-1)
	(caravailable car-2)
	(caravailable car-3)
	(isblueplane plane-2)
	(isblueplane plane-3)
	(isbluestate fl)
	(isbluestate ok)
	(isbluestate wa)
	(isbluestate hi)
    (isblueplane plane-0)
    (isblueplane plane-1)
	(planeavailable plane-0)
	(planeavailable plane-1)
	(planeavailable plane-2)
	(planeavailable plane-3)
))
        