(define (domain rearrangement)
  (:requirements :strips :typing)
  (:types moveable static)
  (:predicates
     (IsRobot ?robot - moveable)
     (IsPawn ?pawn - moveable)
     (IsBear ?bear - moveable)
     (IsGoal ?goal - static)
     (IsMonkey ?monkey - moveable)
     (At ?obj - moveable ?loc - static)
     (Holding ?obj - moveable)
     (Handsfree ?robot - moveable)
     (MoveTo ?loc - static)
     (Pick ?obj - moveable)
     (Place ?obj - moveable)
  )

  ; (:actions MoveTo Pick Place)

  (:action MoveToNotHolding
    :parameters (?robot - moveable ?start - static ?end - static)
    :precondition (and (MoveTo ?end)
                       (IsRobot ?robot)
                       (Handsfree ?robot)
                       (At ?robot ?start)
                  )
    :effect (and (not (At ?robot ?start))
                 (At ?robot ?end)
            )
  )

  (:action MoveToHolding
    :parameters (?robot - moveable ?obj - moveable ?start - static ?end - static)
    :precondition (and (MoveTo ?end)
                       (IsRobot ?robot)
                       (Holding ?obj)
                       (At ?robot ?start)
                       (At ?obj ?start)
                  )
    :effect (and (not (At ?robot ?start))
                 (At ?robot ?end)
                 (not (At ?obj ?start))
                 (At ?obj ?end)
            )
  )

  (:action Pick
    :parameters (?robot - moveable ?obj - moveable ?loc - static)
    :precondition (and (Pick ?obj)
                       (IsRobot ?robot)
                       (Handsfree ?robot)
                       (At ?robot ?loc)
                       (At ?obj ?loc)
                       (not (IsRobot ?obj))
                  )
    :effect (and (Holding ?obj)
                 (not (Handsfree ?robot))
            )
  )

  (:action Place
    :parameters (?robot - moveable ?obj - moveable)
    :precondition (and (Place ?obj)
                       (IsRobot ?robot)
                       (Holding ?obj)
                  )
    :effect (and (not (Holding ?obj))
                 (Handsfree ?robot)
            )
  )
)